//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YogaAppV3._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPos
    {
        public string PoseName { get; set; }
        public string Level { get; set; }
        public string BodyRegion { get; set; }
        public string Modification { get; set; }
        public string BreakDown { get; set; }
        public string ImageName { get; set; }
    }
}
