//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YogaAppV3._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLog
    {
        public string TimeStamp { get; set; }
        public string UserID { get; set; }
        public string LogLvl { get; set; }
        public string LogAreaStretched { get; set; }
        public Nullable<System.TimeSpan> LogTime { get; set; }
        public string LogNumStretch { get; set; }
        public Nullable<System.TimeSpan> LogTimePer { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
