//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YogaAppV3._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSetting
    {
        public string UserID { get; set; }
        public Nullable<bool> Pregnant { get; set; }
        public Nullable<bool> Injured { get; set; }
        public string DifficultyLvl { get; set; }
        public string Injury { get; set; }
        public Nullable<bool> Meditation { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
